local DrawSpaceShipMenu = {}
DrawSpaceShipMenu.__index = DrawSpaceShipMenu
local font2 = love.graphics.newFont("fonts/alien.ttf", 20)
local font = love.graphics.newFont("fonts/alien.ttf", 25)
local sprites = {}
sprites.bigplayerlvl1 = love.graphics.newImage('sprites/player/bigplayer1.png')
sprites.bigplayerlvl2 = love.graphics.newImage('sprites/player/bigplayer2.png')
sprites.bigplayerlvl3 = love.graphics.newImage('sprites/player/bigplayer3.png')
sprites.bigplayerlvl4 = love.graphics.newImage('sprites/player/bigplayer4.png')
sprites.blackhole = love.graphics.newImage("sprites/blackhole.png")
local scale = 0.5
local scale2 = 0.15
function DrawSpaceShipMenu.new()
    local self = setmetatable({}, DrawSpaceShipMenu)
    return self
end
function DrawSpaceShipMenu:draw()
    Data.player.lvl = math.min(Data.shield.lvl, Data.bomb.lvl, Data.gun.lvl)
        if Data.player.lvl == 1 then
        sprites.playerlvl0 = sprites.bigplayerlvl1
        elseif Data.player.lvl == 2 then
        sprites.playerlvl0 = sprites.bigplayerlvl2
        elseif Data.player.lvl == 3 then
        sprites.playerlvl0 = sprites.bigplayerlvl3
        elseif Data.player.lvl == 4 then
        sprites.playerlvl0 = sprites.bigplayerlvl4
        end
        love.graphics.setColor(1, 0.6, 0)
        love.graphics.rectangle("fill", 935, 20, 590, 300)
        love.graphics.setColor(0, 0, 0)
        love.graphics.rectangle("fill", 940, 25, 580, 290)
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.setColor(1, 0.6, 0)
        love.graphics.print("LASER LVL: " ..  Data.gun.lvl, 1130, 50)
        love.graphics.print("BOMB LVL: " ..  Data.bomb.lvl, 1130, 80)
        love.graphics.print("SHIELD LVL: " .. Data.shield.lvl, 1130, 110)
        love.graphics.print("SPEED BULLET LVL: " .. Data.speedbullet.lvl, 1130, 140)
        love.graphics.print("SPEED MOVEMENT LVL: " ..  Data.speedmovement.lvl, 1130, 170)
        love.graphics.print("FIRERATE LVL: " ..  Data.firerate.lvl, 1130, 200)
        love.graphics.print("SPACESHIP LVL: " .. Data.lvl , 1130, 230)
        love.graphics.print("LIFEPOINTS: " .. Data.player.lifepoints , 1130, 270)
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.setFont(font2)
        if Data.currentState == "shieldspaceshipmenu" then
            love.graphics.print(Data.shield.lvl1.TimerMax, 750, 205)
            love.graphics.print(Data.shield.lvl1.CooldownMax, 770, 235)
            love.graphics.print(Data.shield.lvl2.TimerMax, 750, 362)
            love.graphics.print(Data.shield.lvl2.CooldownMax, 770, 393)
            love.graphics.print(Data.shield.lvl3.TimerMax, 750, 519)
            love.graphics.print(Data.shield.lvl3.CooldownMax, 770, 551)
            love.graphics.print(Data.shield.lvl4.TimerMax, 750, 676)
            love.graphics.print(Data.shield.lvl4.CooldownMax, 770, 709)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.shield.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.shield.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.shield.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        elseif Data.currentState == "laserspaceshipmenu" then
            love.graphics.print(Data.gun.lvl1.TimerMax, 750, 205)
            love.graphics.print(Data.gun.lvl1.CooldownMax, 770, 235)
            love.graphics.print(Data.gun.lvl2.TimerMax, 750, 362)
            love.graphics.print(Data.gun.lvl2.CooldownMax, 770, 393)
            love.graphics.print(Data.gun.lvl3.TimerMax, 750, 519)
            love.graphics.print(Data.gun.lvl3.CooldownMax, 770, 551)
            love.graphics.print(Data.gun.lvl4.TimerMax, 750, 676)
            love.graphics.print(Data.gun.lvl4.CooldownMax, 770, 709)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.gun.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.gun.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.gun.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        elseif Data.currentState == "bombspaceshipmenu" then
            love.graphics.print(Data.bomb.lvl1.radius, 720, 205)
            love.graphics.print(Data.bomb.lvl1.CooldownMax, 770, 235)
            love.graphics.print(Data.bomb.lvl2.radius, 720, 362)
            love.graphics.print(Data.bomb.lvl2.CooldownMax, 770, 393)
            love.graphics.print(Data.bomb.lvl3.radius, 720, 519)
            love.graphics.print(Data.bomb.lvl3.CooldownMax, 770, 551)
            love.graphics.print(Data.bomb.lvl4.radius, 720, 676)
            love.graphics.print(Data.bomb.lvl4.CooldownMax, 770, 709)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.bomb.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.bomb.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.bomb.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        elseif Data.currentState == "fireratespaceshipmenu" then
            love.graphics.print(Data.firerate.lvl1.shootTimerMax, 740, 217)
            love.graphics.print(Data.firerate.lvl2.shootTimerMax, 740, 375)
            love.graphics.print(Data.firerate.lvl3.shootTimerMax, 740, 533)
            love.graphics.print(Data.firerate.lvl4.shootTimerMax, 740, 691)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.firerate.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.firerate.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.firerate.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        elseif Data.currentState == "speedmovementspaceshipmenu" then
            love.graphics.print(Data.speedmovement.lvl1.value, 770, 217)
            love.graphics.print(Data.speedmovement.lvl2.value, 770, 375)
            love.graphics.print(Data.speedmovement.lvl3.value, 770, 533)
            love.graphics.print(Data.speedmovement.lvl4.value, 770, 691)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedmovement.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedmovement.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedmovement.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        elseif Data.currentState == "speedbulletspaceshipmenu" then
            love.graphics.print(Data.speedbullet.lvl1.value, 780, 217)
            love.graphics.print(Data.speedbullet.lvl2.value, 780, 375)
            love.graphics.print(Data.speedbullet.lvl3.value, 780, 533)
            love.graphics.print(Data.speedbullet.lvl4.value, 780, 691)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.rectangle("fill", 100, 580, 220, 220)
            love.graphics.setColor(0, 0, 0)
            love.graphics.rectangle("fill", 105, 585, 210, 210)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL2 COST:", 140, 600)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedbullet.lvl1, 140, 630)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL3 COST:", 140, 660)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedbullet.lvl2, 140, 690)
            love.graphics.setColor(1, 0.6, 0)
            love.graphics.print("LVL4 COST:", 140, 720)
            love.graphics.setColor(1, 1, 1, 1)
            love.graphics.print(Data.powerscost.speedbullet.lvl3, 140, 750)
            love.graphics.setColor(1, 0.6, 0)
        end
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.setFont(font)
        love.graphics.print(Data.player.money , 1000, 50)
        love.graphics.setColor(1, 0.6, 0)
        love.graphics.rectangle("fill", 995, 395, 410, 410)
        love.graphics.setColor(0, 0, 0)
        love.graphics.rectangle("fill", 1000, 400, 400, 400)
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.draw(sprites.playerlvl0, 1065, 480, 0, scale, scale)
        love.graphics.setColor(1, 0.6, 0)
        love.graphics.print("PL.LVL: " .. Data.player.lvl, 1030, 420)
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.draw(sprites.blackhole, 980, 100, 0, scale2, scale2)
end

return DrawSpaceShipMenu