Data = {
    lvl = 1,
    shield = {
        lvl = 1,
        active = false,
        lvl1 = {
            CooldownMax = 20, 
            Cooldown = 0, 
            TimerMax = 2, 
            current = true,
    },
        lvl2 = {            
            CooldownMax = 15, 
            Cooldown = 0, 
            TimerMax = 3,
            current = false,
        },
        lvl3 = {            
            CooldownMax = 10, 
            Cooldown = 0, 
            TimerMax = 4,
            current = false,
        },
        lvl4 = {            
            CooldownMax = 7, 
            Cooldown = 0, 
            TimerMax = 5,
            current = false,
        },
    },
    bomb = {
        lvl = 1,
        active = false,
        lvl1 = {
            CooldownMax = 20, 
            Cooldown = 0, 
            TimerMax = 0.1,
            radius = 100,
            current = true,
            scaleX = 20,
            scaleY = 20,
        },
        lvl2 = {            
            CooldownMax = 15, 
            Cooldown = 0, 
            TimerMax = 0.1,
            radius = 200,
            current = false,
            scaleX = 60,
            scaleY = 60,
        },
        lvl3 = {            
            CooldownMax = 10, 
            Cooldown = 0, 
            TimerMax = 0.1,
            radius = 300,
            current = false,
            scaleX = 90,
            scaleY = 90,
        },
        lvl4 = {            
            CooldownMax = 7, 
            Cooldown = 0, 
            TimerMax = 0.1,
            radius = 400,
            current = false,
            scaleX = 120,
            scaleY = 120,
        },
    },
    gun = {
        active = false,
        lvl = 1,
        lvl1 = {
            CooldownMax = 20, 
            Cooldown = 0, 
            TimerMax = 2,
            shootTimerMax = 0.4,
            current = true,
        },
        
        lvl2 = {            
            CooldownMax = 15, 
            Cooldown = 0, 
            TimerMax = 2.5,
            shootTimerMax = 0.3,
            current = false,
        },
        lvl3 = {            
            CooldownMax = 10, 
            Cooldown = 0, 
            TimerMax = 3,
            shootTimerMax = 0.2,
            current = false,
        },
        lvl4 = {            
            CooldownMax = 7, 
            Cooldown = 0, 
            TimerMax = 4,
            shootTimerMax = 0.1,
            current = false,
        },
    },
    firerate = {
        lvl = 1,
        lvl1 = {
            shootTimerMax = 0.9,
            current = true,
        },
        lvl2 = {            
            shootTimerMax = 0.6,
            current = false,
        },
        lvl3 = {            
            shootTimerMax = 0.4,
            current = false,
        },
        lvl4 = {            
            shootTimerMax = 0.2,
            current = false,
        },
    },
    speedbullet = {
        lvl = 1,
        lvl1 = {
            current = true,
            value = 300,
        },
        
        lvl2 = {            
            current = false,
            value = 500,
        },
        lvl3 = {            
            current = false,
            value = 700,
        },
        lvl4 = {            
            current = false,
            value = 900,
        },
    },
    speedmovement = {
        lvl = 1,
        lvl1 = {            
            current = false,
            value = 150,
        },
        lvl2 = {            
            current = false,
            value = 250,
        },
        lvl3 = {            
            current = false,
            value = 350,
        },
        lvl4 = {            
            current = false,
            value = 450,
        },
    },
    sprites = {
        playerlvl0 = love.graphics.newImage('sprites/player/player1.png'), 
        playerlvl1 = love.graphics.newImage('sprites/player/player2.png'), 
        playerlvl2 = love.graphics.newImage('sprites/player/player3.png'), 
        playerlvl3 = love.graphics.newImage('sprites/player/player4.png'), 
        bigplayerlvl0 = love.graphics.newImage('sprites/player/player1.png'), 
        bigplayerlvl1 = love.graphics.newImage('sprites/player/player2.png'), 
        bigplayerlvl2 = love.graphics.newImage('sprites/player/player3.png'), 
        bigplayerlvl3 = love.graphics.newImage('sprites/player/player4.png'), 
    },
    powerscost = {
        shield = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
        gun = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
        bomb = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
        speedbullet = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
        speedmovement = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
        firerate = {
            lvl1 = 200, 
            lvl2 = 350, 
            lvl3 = 500, 
        },
    },  
    levelbloq = false,
    lvl1completed = false,
    lvl2completed = false,
    lvl3completed = false,
    lvl4completed = false,
    lvl5completed = false,
    lvl6completed = false,
    lvl7completed = false,
    lvl8completed = false,
    lvl9completed = false,
    lvl10completed = false,
    lvl11completed = false,
    lvl12completed = false,
    lvl13completed = false,
    lvl14completed = false,
    lvl15completed = false,
    windowWidth = love.graphics.getWidth(),
    windowHeight = love.graphics.getHeight(),
    player = {
        deadgameenemies = 0,
        deadtotalenemies = 0,
        lvl = 1,
        lvl0 = true,
        lvl1 = false, 
        lvl2 = false,
        lvl3 = false,
        speedmovementlvl1 = 150,
        speedmovementlvl2 = 200,
        speedmovementlvl3 = 300,
        speedmovementlvl4 = 400,
        speedbulletlvl1 = 1000,
        speedbulletlvl2 = 200,
        speedbulletlvl3 = 300,
        speedbulletlvl4 = 400,
        ---
        money = 0,
        lifepoints = 200;
        cometsintercepted = 0,
        name = "",
    },
    lvl1 = {--be
        enemy1 = {speed = 130, maxTime = 0.5},
        --enemy2 = {speed = 70, maxTime = 1, fireRate = 1.2, bulletSpeed = 600},
        --enemy3 = {speed = 100, maxTime = 1, fireRate = 1.2, bulletSpeed = 600},
        --enemy4 = {speed = 100, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 1.2, bulletSpeed = 600},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 1.2, bulletSpeed = 600},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 40,
    },
    lvl2 = {--be
        enemy1 = {speed = 130, maxTime = 0.5},
        enemy2 = {speed = 70, maxTime = 4.5, fireRate = 3, bulletSpeed = 350},
        --enemy3 = {speed = 100, maxTime = 1, fireRate = 1.1, bulletSpeed = 620},
        --enemy4 = {speed = 100, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 1.1, bulletSpeed = 620},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 1.1, bulletSpeed = 620},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 50,
    },
    lvl3 = { --be
        enemy1 = {speed = 130, maxTime = 1.3},
        enemy2 = {speed = 70, maxTime = 3, fireRate = 3, bulletSpeed = 300},
        --enemy3 = {speed = 100, maxTime = 1, fireRate = 1, bulletSpeed = 640},
        --enemy4 = {speed = 100, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 1, bulletSpeed = 640},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 1, bulletSpeed = 640},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 60,
    },
    lvl4 = { --be
        enemy1 = {speed = 100, maxTime = 1.2},
        --enemy2 = {speed = 70, maxTime = 1.50, fireRate = 1.3, bulletSpeed = 400},
        enemy3 = {speed = 50, maxTime = 3.5, fireRate = 2.5, bulletSpeed = 500},
        --enemy4 = {speed = 100, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 0.9, bulletSpeed = 660},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 0.9, bulletSpeed = 660},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 70,
    },
    lvl5 = { --be
        enemy1 = {speed = 100, maxTime = 4},
        enemy2 = {speed = 70, maxTime = 2.5, fireRate = 3, bulletSpeed = 300},
        enemy3 = {speed = 50, maxTime = 3.5, fireRate = 2.5, bulletSpeed = 500},
        --enemy4 = {speed = 100, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 0.8, bulletSpeed = 680},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 0.8, bulletSpeed = 680},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 80,
    },
    lvl6 = {--be
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1, fireRate = 0.7, bulletSpeed = 500},
        --enemy3 = {speed = 70, maxTime = 1, fireRate = 0.7, bulletSpeed = 600},
        enemy4 = {speed = 175, maxTime = 0.5},
        --enemy5 = {speed = 100, maxTime = 1, fireRate = 0.7, bulletSpeed = 700},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 0.7, bulletSpeed = 700},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 90,
    },
    lvl7 = { --be
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1, fireRate = 1.3, bulletSpeed = 720},
        --enemy3 = {speed = 70, maxTime = 1, fireRate = 0.6, bulletSpeed = 720},
        enemy4 = {speed = 150, maxTime = 1.2},
        enemy5 = {speed = 100, maxTime = 2.5, fireRate = 2.5, bulletSpeed = 400},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 0.6, bulletSpeed = 720},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 100,
    },
    lvl8 = {--be
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1.56, fireRate = 0.5, bulletSpeed = 740},
        enemy3 = {speed = 50, maxTime = 4.5, fireRate = 2.5, bulletSpeed = 500},
        enemy4 = {speed = 175, maxTime = 2},
        enemy5 = {speed = 100, maxTime = 2.5, fireRate = 2.5, bulletSpeed = 400},
        --enemy6 = {speed = 60, maxTime = 1, fireRate = 2, bulletSpeed = 550},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 110,
    },
    lvl9 = {--be
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1.04, fireRate = 0.4, bulletSpeed = 760},
        enemy3 = {speed = 50, maxTime = 4, fireRate = 2.5, bulletSpeed = 450},
        enemy4 = {speed = 175, maxTime = 2},
        enemy5 = {speed = 100, maxTime = 2, fireRate = 2.5, bulletSpeed = 400},
        --enemy6 = {speed = 100, maxTime = 1, fireRate = 0.4, bulletSpeed = 760},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 110,
    },
    lvl10 = {
        enemy1 = {speed = 100, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1, fireRate = 0.3, bulletSpeed = 780},
        --enemy3 = {speed = 70, maxTime = 3.13, fireRate = 0.3, bulletSpeed = 780},
        --enemy4 = {speed = 110, maxTime = 0.63},
        --enemy5 = {speed = 100, maxTime = 0.83, fireRate = 0.3, bulletSpeed = 780},
        enemy6 = {speed = 80, maxTime = 3, fireRate = 2, bulletSpeed = 650},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 120,
    },
    lvl11 = {
        --enemy1 = {speed = 90, maxTime = 1},
        enemy2 = {speed = 70, maxTime = 1, fireRate = 3, bulletSpeed = 300},
        --enemy3 = {speed = 70, maxTime = 1, fireRate = 0.7, bulletSpeed = 720},
        --enemy4 = {speed = 110, maxTime = 0.87},
        enemy5 = {speed = 100, maxTime = 2.5, fireRate = 2.5, bulletSpeed = 400},
        --enemy6 = {speed = 80, maxTime = 1, fireRate = 0.7, bulletSpeed = 720},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 130,
    },
    lvl12 = {
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1.56, fireRate = 0.6, bulletSpeed = 740},
        enemy3 = {speed = 50, maxTime = 1.8, fireRate = 2.5, bulletSpeed = 500},
        enemy4 = {speed = 175, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 1.56, fireRate = 0.6, bulletSpeed = 740},
        --enemy6 = {speed = 80, maxTime = 1, fireRate = 0.6, bulletSpeed = 740},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 140,
    },
    lvl13 = {
        enemy1 = {speed = 100, maxTime = 1.8},
        --enemy2 = {speed = 70, maxTime = 1.04, fireRate = 0.5, bulletSpeed = 760},
        enemy3 = {speed = 50, maxTime = 2.5, fireRate = 2.5, bulletSpeed = 450},
        --enemy4 = {speed = 110, maxTime = 0.67},
        --enemy5 = {speed = 100, maxTime = 1.04, fireRate = 0.5, bulletSpeed = 760},
        enemy6 = {speed = 80, maxTime = 4.5, fireRate = 2, bulletSpeed = 650},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 150,
    },
    lvl14 = {
        enemy1 = {speed = 100, maxTime = 1},
        enemy2 = {speed = 70, maxTime = 3, fireRate = 3, bulletSpeed = 300},
        --enemy3 = {speed = 70, maxTime = 1, fireRate = 0.4, bulletSpeed = 780},
        enemy4 = {speed = 175, maxTime = 1},
        --enemy5 = {speed = 100, maxTime = 0.83, fireRate = 0.4, bulletSpeed = 780},
        --enemy6 = {speed = 80, maxTime = 1, fireRate = 0.4, bulletSpeed = 780},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 160,
    },
    lvl15 = {
        --enemy1 = {speed = 90, maxTime = 1},
        --enemy2 = {speed = 70, maxTime = 1, fireRate = 0.3, bulletSpeed = 800},
        --enemy3 = {speed = 70, maxTime = 1, fireRate = 0.3, bulletSpeed = 800},
        enemy4 = {speed = 175, maxTime = 1},
        enemy5 = {speed = 100, maxTime = 1.5, fireRate = 2.5, bulletSpeed = 400},
        enemy6 = {speed = 80, maxTime = 2.5, fireRate = 2, bulletSpeed = 650},
        completed = false,
        deadgameenemies = 0,
        lifepointsgained = 0,
        points = 5,
        maxKills = 170,
    }
    }
    Data.__index = Data
    function Data:setCurrentStage(state)
        self.currentState = state
    end
    function Data:setCurrentShield(shiled)
        self.currentShiled = shiled
    end
    function Data:computeRun()
        local totalMoney = 0
        for i = 1, 15 do
            local lvl = self["lvl" .. i]
            totalMoney = totalMoney + ((lvl and lvl.points) or 0)
        end
        return {
            name = self.player.name,
            score = totalMoney,
            aliens = self.player.deadtotalenemies,
            comets  = self.player.cometsintercepted,
            lifepoints = self.player.lifepoints,
        }
    end
    function ResetData()
    end
return Data